(self.AMP=self.AMP||[]).push({n:"amp-sidebar",v:"1901081935550",f:(function(AMP,_){
var f="function"==typeof Object.create?Object.create:function(a){function b(){}b.prototype=a;return new b},l;if("function"==typeof Object.setPrototypeOf)l=Object.setPrototypeOf;else{var m;a:{var n={a:!0},p={};try{p.__proto__=n;m=p.a;break a}catch(a){}m=!1}l=m?function(a,b){a.__proto__=b;if(a.__proto__!==b)throw new TypeError(a+" is not extensible");return a}:null}var q=l;function u(a){return a?Array.prototype.slice.call(a):[]};self.log=self.log||{user:null,dev:null,userForEmbed:null};var v=self.log;function w(a,b){if(!v.user)throw Error("failed to call initLogConstructor");return v.user.assert(a,'"toolbar-target" is required',b,void 0,void 0,void 0,void 0,void 0,void 0,void 0,void 0)};function x(a,b){var c,d=a.ownerDocument.defaultView,e=d!=(d.__AMP_TOP||d);if(e){if(y(d,b)){var g=z(d,b);if(g)return g}if(!c)return null}a=A(a);a=B(a);return y(a,b)?z(a,b):null}function D(a,b){a=a.__AMP_TOP||a;return z(a,b)}function E(a){var b=A(a);b=B(b);return z(b,"history")}function A(a){return a.nodeType?D((a.ownerDocument||a).defaultView,"ampdoc").getAmpDoc(a):a}function B(a){a=A(a);return a.isSingleDoc()?a.win:a}
function z(a,b){y(a,b);var c=a.services;c||(c=a.services={});var d=c;a=d[b];a.obj||(a.obj=new a.ctor(a.context),a.ctor=null,a.context=null,a.resolve&&a.resolve(a.obj));return a.obj}function y(a,b){a=a.services&&a.services[b];return!(!a||!a.ctor&&!a.obj)};/*
 https://mths.be/cssescape v1.5.1 by @mathias | MIT license */
function F(a,b){for(var c,d=a;d&&d!==c;d=d.parentElement)if(b(d))return d;return null}function G(a,b){if(a.closest)return a.closest(b);b=b.toUpperCase();return F(a,function(a){return a.tagName==b})}function H(a){var b=a.body.getAttribute("dir")||a.documentElement.getAttribute("dir")||"ltr";return"rtl"==b};var I,J="Webkit webkit Moz moz ms O o".split(" ");function K(a,b){void 0===b&&(b=a.hasAttribute("hidden"));b?a.removeAttribute("hidden"):a.setAttribute("hidden","")};function L(a,b){this.I=b;this.c=a;this.D=b.getAmpDoc();this.R=this.c.getAttribute("toolbar");this.B=null;this.h=void 0;this.C=!1;this.c.classList.add("amp-sidebar-toolbar-target-hidden");M(this)}L.prototype.onLayoutChange=function(){var a=this.D.win.matchMedia(this.R).matches;a?N(this):O(this)};
function M(a){a.B=a.c.cloneNode(!0);var b=w(a.c.getAttribute("toolbar-target"),a.c);a.D.whenReady().then(function(){var c=a.D.getElementById(b);if(c)a.h=c,a.B.classList.add("i-amphtml-toolbar"),K(a.h,!1);else throw Error("Could not find the toolbar-target element with an id: "+b);})}
function N(a){a.C?Promise.resolve():a.I.mutateElement(function(){a.h&&(K(a.h,!0),a.h.contains(a.B)||a.h.appendChild(a.B),a.c.classList.add("amp-sidebar-toolbar-target-shown"),a.c.classList.remove("amp-sidebar-toolbar-target-hidden"),a.C=!0)})}function O(a){a.C&&a.I.mutateElement(function(){a.h&&(K(a.h,!1),a.c.classList.add("amp-sidebar-toolbar-target-hidden"),a.c.classList.remove("amp-sidebar-toolbar-target-shown"),a.C=!1)})};function Q(a){var b=a.indexOf("#");return-1==b?a:a.substring(0,b)};function R(a){a=AMP.BaseElement.call(this,a)||this;a.m=null;a.G=null;a.M=null;a.o=null;a.l=a.win.document;a.N=a.l.documentElement;a.w=null;a.L=[];var b=D(a.win,"platform");a.K=b.isIos();a.O=b.isSafari();a.A=-1;a.H=!1;a.F=null;a.J=0;return a}var S=AMP.BaseElement;R.prototype=f(S.prototype);R.prototype.constructor=R;if(q)q(R,S);else for(var T in S)if("prototype"!=T)if(Object.defineProperties){var U=Object.getOwnPropertyDescriptor(S,T);U&&Object.defineProperty(R,T,U)}else R[T]=S[T];R.S=S.prototype;
R.prototype.buildCallback=function(){var a=this,b=this.element;b.classList.add("i-amphtml-overlay");b.classList.add("i-amphtml-scrollable");this.w=b.getAttribute("side");this.m=this.getViewport();this.G=x(b,"action");"left"!=this.w&&"right"!=this.w&&(this.w=V(this,H(this.l)?"right":"left"),b.setAttribute("side",this.w));var c=u(b.querySelectorAll("nav[toolbar]"));c.forEach(function(b){try{a.L.push(new L(b,a))}catch(h){a.user().error("amp-sidebar toolbar","Failed to instantiate toolbar",h)}});this.K&&
aa(this);W(this)?X(this):b.setAttribute("aria-hidden","true");b.hasAttribute("role")||b.setAttribute("role","menu");b.tabIndex=-1;this.N.addEventListener("keydown",function(b){"Escape"==b.key&&(b.preventDefault(),a.j())});var d=b.getAttribute("data-close-button-aria-label")||"Close the sidebar",e=this.l.createElement("button");e.textContent=d;e.classList.add("i-amphtml-screen-reader");e.tabIndex=-1;e.addEventListener("click",function(){a.j()});b.appendChild(e);this.registerDefaultAction(function(b){return X(a,
b)},"open");this.registerAction("toggle",this.P.bind(this));this.registerAction("close",this.j.bind(this));b.addEventListener("click",function(c){if((c=G(c.target,"A"))&&c.href){var d=x(b,"url").parse(c.href),e=a.getAmpDoc().win.location.href;Q(c.href)==Q(e)&&d.hash&&a.j()}},!0)};R.prototype.onLayoutMeasure=function(){var a=this;this.getAmpDoc().whenReady().then(function(){a.L.forEach(function(a){a.onLayoutChange()})})};function W(a){return a.element.hasAttribute("open")}
R.prototype.P=function(a){W(this)?this.j():X(this,a)};function Y(a,b,c){function d(){a.M===b&&a.mutateElement(b)}a.M=b;c?D(a.win,"timer").delay(d,c):d()}function ba(a){K(a.element,!0);a.m.addToFixedLayer(a.element,!0);a.K&&a.O&&ca(a);a.element.scrollTop=1;Y(a,function(){return da(a)})}
function da(a){ea(a);a.element.setAttribute("open","");a.element.setAttribute("aria-hidden","false");Y(a,function(){var b=a.getRealChildren();a.scheduleLayout(b);a.scheduleResume(b);try{a.element.focus()}catch(c){}Z(a,"sidebarOpen")},350)}function fa(a){a.o&&a.o.classList.toggle("i-amphtml-ghost",!0);a.element.removeAttribute("open");a.element.setAttribute("aria-hidden","true");Y(a,function(){K(a.element,!1);a.schedulePause(a.getRealChildren());Z(a,"sidebarClose")},350)}
function X(a,b){W(a)||(a.m.enterOverlayMode(),Y(a,function(){return ba(a)}),E(a.getAmpDoc()).push(a.j.bind(a)).then(function(b){a.A=b}),b&&(a.F=b.caller,a.J=a.m.getScrollTop()))}R.prototype.j=function(){var a=this;if(W(this)){this.m.leaveOverlayMode();var b=this.J==this.m.getScrollTop(),c=this.element.contains(this.l.activeElement);Y(this,function(){return fa(a)});-1!=this.A&&(E(this.getAmpDoc()).pop(this.A),this.A=-1);if(this.F&&c&&b)try{this.F.focus()}catch(d){}}};
function V(a,b){return G(a.element,"amp-story")?"left"==b?"right":"left":b}function ea(a){if(!a.o){var b=a.l.createElement("div");b.classList.add("i-amphtml-sidebar-mask");b.addEventListener("click",function(){a.j()});a.element.ownerDocument.body.appendChild(b);b.addEventListener("touchmove",function(a){a.preventDefault()});a.o=b}a.o.classList.toggle("i-amphtml-ghost",!1)}
function aa(a){a.element.addEventListener("scroll",function(b){W(a)&&(1>a.element.scrollTop?(a.element.scrollTop=1,b.preventDefault()):a.element.scrollHeight==a.element.scrollTop+a.element.offsetHeight&&(--a.element.scrollTop,b.preventDefault()))})}
function ca(a){if(!a.H){var b=a.l.createElement("div"),c={height:"29px",width:"100%","background-color":"transparent"},d;for(d in c){var e=b,g=c[d];var h=e.style;var k=d;if(2>k.length?0:0==k.lastIndexOf("--",0))h=k;else{I||(I=Object.create(null));var r=I[k];if(!r){r=k;if(void 0===h[k]){var t=k.charAt(0).toUpperCase()+k.slice(1);b:{for(var C=0;C<J.length;C++){var P=J[C]+t;if(void 0!==h[P]){t=P;break b}}t=""}void 0!==h[t]&&(r=t)}I[k]=r}h=r}h&&(e.style[h]=g)}a.element.appendChild(b);a.H=!0}}
function Z(a,b){var c=a.win;var d="amp-sidebar toolbar."+b;var e={};var g={detail:e};Object.assign(g,void 0);"function"==typeof c.CustomEvent?d=new c.CustomEvent(d,g):(c=c.document.createEvent("CustomEvent"),c.initCustomEvent(d,!!g.bubbles,!!g.cancelable,e),d=c);a.G.trigger(a.element,b,d,100)}(function(a){a.registerElement("amp-sidebar",R,"amp-sidebar{position:fixed!important;top:0;max-height:100vh!important;height:100vh;max-width:80vw;background-color:#efefef;min-width:45px!important;outline:none;overflow-x:hidden!important;overflow-y:auto!important;z-index:2147483647;-webkit-overflow-scrolling:touch;will-change:transform}amp-sidebar[side=left]{left:0!important;-webkit-transform:translateX(-100%)!important;transform:translateX(-100%)!important}amp-sidebar[side=right]{right:0!important;-webkit-transform:translateX(100%)!important;transform:translateX(100%)!important}amp-sidebar[side][open]{-webkit-transform:translateX(0)!important;transform:translateX(0)!important}amp-sidebar[side]{-webkit-transition:-webkit-transform 233ms cubic-bezier(0,0,.21,1);transition:-webkit-transform 233ms cubic-bezier(0,0,.21,1);transition:transform 233ms cubic-bezier(0,0,.21,1);transition:transform 233ms cubic-bezier(0,0,.21,1),-webkit-transform 233ms cubic-bezier(0,0,.21,1)}.i-amphtml-toolbar>ul{display:-webkit-box;display:-ms-flexbox;display:flex;-webkit-box-pack:start;-ms-flex-pack:start;justify-content:flex-start;-ms-flex-wrap:wrap;flex-wrap:wrap;overflow:auto;list-style-type:none;padding:0;margin:0}.i-amphtml-sidebar-mask{position:fixed!important;top:0!important;left:0!important;width:100vw!important;height:100vh!important;opacity:0.2;background-image:none!important;background-color:#000;z-index:2147483646}\n/*# sourceURL=/extensions/amp-sidebar/0.1/amp-sidebar.css*/")})(self.AMP);
})});
//# sourceMappingURL=amp-sidebar-0.1.js.map

